//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPriceFetcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\jrpjobsvc\\Downloads")]
        public string DownloadPath {
            get {
                return ((string)(this["DownloadPath"]));
            }
            set {
                this["DownloadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@jasperridge.com")]
        public string EmailDomain {
            get {
                return ((string)(this["EmailDomain"]));
            }
            set {
                this["EmailDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fwrelay.jasperridge.com")]
        public string Smtp {
            get {
                return ((string)(this["Smtp"]));
            }
            set {
                this["Smtp"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQLCLUSTER;Initial Catalog=JRP7012PROD;Integrated Security=True")]
        public string JRP7012Prod {
            get {
                return ((string)(this["JRP7012Prod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQLCLUSTER;Initial Catalog=Bloomberg;Integrated Security=True")]
        public string Bloomberg {
            get {
                return ((string)(this["Bloomberg"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dev@jasperridge.com; b305441f.JasperRidgePartners.onmicrosoft.com@amer.teams.ms;")]
        public string adminEmail {
            get {
                return ((string)(this["adminEmail"]));
            }
            set {
                this["adminEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b305441f.JasperRidgePartners.onmicrosoft.com@amer.teams.ms;")]
        public string TeamsEmail {
            get {
                return ((string)(this["TeamsEmail"]));
            }
            set {
                this["TeamsEmail"] = value;
            }
        }
    }
}
